name: Deploy Site

on: [workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn
        working-directory: ./nestle-site
      - run: yarn deploy
        working-directory: ./nestle-site
